User repos settings updated
ossboard-org/ossboard pull request #111
Opened 2017-03-27 02:41 UTC by alishersadikov

Remove unnecessary files.

2017-03-27 02:49 UTC, alishersadikov commented
@davydovanton sorry I had committed unnecessary files before. Do we need anything else done for this issue?

2017-04-02 15:46 UTC, davydovanton requested changes
Please, revert `Gemfile.lock` changes and fix merge conflicts. Thanks for your work 👍

2017-04-02 15:46 UTC, davydovanton commented on Gemfile.lock
> -GIT
I think we need to revert changes for `Gemfile.lock` file 😊

2017-04-21 03:24 UTC, alishersadikov commented
Sorry, my bad - still learning :)

2019-05-27 11:04 UTC, closed without merging